Numpy assignment 

1. What is a Python library? Why do we use Python libraries?

ans ==> A python library is a collection of pre-written code that provides function , classes,module,  
        perform various kind of task and implement some data.


        1.code reusability
        2.community support
        3.open source
        4.easy to use
        5 standardization

#2. What is the difference between Numpy array and List?

Numpy array --> all element in a numpy array must have 
 same data type

example --> np.array([1,23,2])


list --> python store heterogenous data like boolean ,int, float,str,etc
        list are slower when it ocmes in numerical operation because
they implemented in python and more general purpose.

example --> l [2,3,'Aryan','Yadav',True,2]

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [18]:
import numpy as np
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

In [19]:
arr.shape

(3, 4)

In [20]:
arr.size

12

In [21]:
arr.ndim

2

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [22]:
firstRow = arr[0]
firstRow

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [23]:
third_row_forth_col = arr[2,3]

In [24]:
third_row_forth_col

np.int64(12)


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [25]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2] 

print(odd_indexed_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?



In [26]:
rand_matrix = np.random.rand(3,3)
rand_matrix

array([[0.1493756 , 0.2554915 , 0.60854244],
       [0.25592679, 0.90267195, 0.24326119],
       [0.69458633, 0.3734237 , 0.34543851]])

In [27]:
rInt_matrix = np.random.randint(low = 0,high = 20,size = (3,3))
rInt_matrix

array([[ 5, 13, 15],
       [ 5, 14,  5],
       [13, 18, 18]])

8. Describe the difference between np.random.rand and np.random.randn?


1. --> Use np.random.rand when you need random numbers 
that are equally likely to occur within a specific range.

2. --> Use np.random.randn when you need random numbers that
are more likely to be close to the mean and less likely to be far from it.

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [28]:
expand_arr = np.expand_dims(arr,axis = 0)
expand_arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [29]:
expand_arr.ndim

3

. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [30]:
# i would use T attribute for transpose the array
transpose = arr.T
transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

 11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python
1,+ Index wise multiplicatio'
2.Matrix multiplicatio'
3.Add both the matricK
4.Subtract matrix B from 
5. Divide Matrix B by A

In [31]:
matrix1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])



In [32]:
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
matrix2 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])


In [34]:
# index wise mulitplication
mult = matrix1*matrix2
mult

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [35]:
mtx_mlt = np.dot(matrix1,matrix2.T)
mtx_mlt

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [36]:
# add both matrix
add = matrix1+matrix2
add

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [37]:
sub = matrix1-matrix2
sub

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
div =matrix1/matrix2
div

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte order of an array?

numpy.ndarray.byteswap(inplace=False)
this function use to swap the byte order of an array


13.  What is the significance of the np.linalg.inv function?

The np.linalg.inv() function in NumPy is used to compute the inverse of a given square matrix.

14. What does the np.reshape function do, and how is it used?


The np.reshape() function in NumPy is used to change the shape or dimensions of an existing NumPy array without changing its data.

15. What is broadcasting in Numpy?

broadcasting allows NumPy to perform operations on arrays of different shapes by automatically adjusting their sizes to match.